name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Testing on Node.js v20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: actions/checkout@v2
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test
